[package]
name = "ttlless"
version = "0.1.0"
edition = "2024"

[dependencies]
rio_api = "0.8.4"
rio_turtle = "0.8.4"
colored = "2.0.4"
clap = { version = "4.4.11", features = ["derive"] }
anyhow = "1.0.75"
